title: LoveSarah, inc
slogan: This blog is a work in progress. No more perfection just adventure. Enjoy!
author: Sarah Prasuhn
url: http://lovesarahinc.com

auto: false
pygments: true
lsi: false
markdown: rdiscount
permalink: blog/:title
exclude: Gemfile, Gemfile.lock, Rakefile, aws_cf_sync.rb, s3.config, aws_cf_invalidate.rb
