title: mikeyp.net
slogan: confusing archaeologists since 1981
author: Michael Prasuhn
url: http://mikeyp.net

auto: false
pygments: true
lsi: false
markdown: rdiscount
permalink: blog/:title
exclude: Gemfile, Gemfile.lock, Rakefile, aws_cf_sync.rb, s3.config, aws_cf_invalidate.rb
